name: "🐞 Bug Report"
description: Report a reproducible problem in the app
title: "bug: <short description>"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all required fields. Incomplete issues may be closed.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug.
      placeholder: e.g. Dashboard crashes when switching language
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the problem and any context.
      placeholder: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Numbered minimal steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: It should...
    validations:
      required: true
  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: It actually...
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - critical (data loss / crash)
        - high (major feature broken)
        - medium (workaround exists)
        - low (cosmetic / minor)
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: macOS 14 / Chrome 127 / Node 20.x
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Console Output
      render: shell
      description: Paste relevant logs (trim to essentials).
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Recordings
      description: Drag & drop images or videos.
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I searched existing issues / discussions
          required: true
        - label: I can reproduce with latest main
          required: true
        - label: I provided minimal repro steps
          required: true
