blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/lucferbux/react-portfolio-dash/security/policy
    about: Please report security issues via the security policy.
